version: '3.8'
services:
  postgres-beautique:
    image: postgres
    hostname: postgres-beautique
    environment:
      POSTGRES_DB: beautique
      POSTGRES_USER: beautique
      POSTGRES_PASSWORD: beautique
    ports:
      - 3334:5432
    networks:
      - beautique-network
  rabbitmq:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - beautique-network          
  mongodb:
    image: 'mongo:latest'
    hostname: 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - '27017:27017'
    networks:
      - beautique-network  
networks:
  beautique-network:
    driver: bridge