spring:
  application:
    name: beautique
  datasource:
    url: jdbc:postgresql://localhost:3334/beautique
    username: beautique
    password: beautique
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: beautique_schema
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  servlet:
    context-path: /ms-beautique
  port: 8082